### ISSUE TITLE
consider using tower

### ISSUE THREAD

**Issue by Emilgardis** [twitch-rs/twitch_api#144]
https://crates.io/crates/tower-service

**Comment by simonsan** [comment]
I announce my interest in getting to know what you imagine using towers `service` trait for?

**Comment by Emilgardis** [comment]
This is solved, kinda. There is an argument though for replacing [`Client::req`](https://github.com/twitch-rs/twitch_api/blob/462f602f5b3042cd27f0e41da1f0c69234f256ec/src/client.rs#L178) with [`Service::call`](https://docs.rs/tower/0.4.13/tower/trait.Service.html#tymethod.call)

The reson for doing this is that `Service` is better for composing.
