### ISSUE TITLE
Impossible to use requests / body with DeserializeOwned

### ISSUE THREAD

**Issue by Emilgardis** [twitch-rs/twitch_api#284]
How does one solve the following

```rust
#[derive(Debug, serde::Deserialize)]
struct Reward {
    #[serde(bound(
        deserialize = "twitch_api::helix::points::UpdateCustomRewardBody<'static>: serde::Deserialize<'de>"
    ))]
    other: twitch_api::helix::points::UpdateCustomRewardBody<'static>,
}

pub fn deser<T: serde::de::DeserializeOwned>(_t: T) {}

pub fn test() {
    let reward = Reward {
        other: Default::default(),
    };
    deser(reward);
}
```

```
❯ cargo check
    Checking twitch_api_owned v0.1.0 (/Users/emil/workspace/dev_space/twitch_api_owned)
error: implementation of `Deserialize` is not general enough
  --> src/lib.rs:15:5
   |
15 |     deser(reward);
   |     ^^^^^^^^^^^^^ implementation of `Deserialize` is not general enough
   |
   = note: `Reward` must implement `Deserialize<'0>`, for any lifetime `'0`...
   = note: ...but it actually implements `Deserialize<'1>`, for some specific lifetime `'1`

error: could not compile `twitch_api_owned` due to previous error
```

this issue presents with `actix-web` where you do something like

```rust
#[actix_web::post("update")]
async fn rewards_update(
    update: web::Json<RewardEdit>,
) -> Result<HttpResponse, Box<dyn std::error::Error + 'static>> {
todo!()
}
```
where `web::Json<T: DeserializeOwned>`

related: https://github.com/serde-rs/serde/issues/1712

the above issue [mentions](https://github.com/serde-rs/serde/issues/1712#issuecomment-1216221853) using `#[serde(bound(deserialize = "twitch_api::helix::points::UpdateCustomRewardBody<'static>: serde::Deserialize<'de>"))]` but that does not seem to work

**Comment by Emilgardis** [comment]
If we remove the `#[serde(borrow)]` on the request, this works just as one would like, but that means that the data would never be borrowed

**Comment by Nerixyz** [comment]
I personally wouldn't mind not borrowing when deserializing (for now), since the requests are mainly used for serializing. Maybe this could be a feature-flag?

**Comment by Emilgardis** [comment]
That sounds good. I do feel like this is solvable though, I'm wondering why the solution in https://github.com/serde-rs/serde/issues/1712 doesn't work

**Comment by Emilgardis** [comment]
this might be relevant https://github.com/serde-rs/serde/issues/2016#issuecomment-1027280828

**Comment by Emilgardis** [comment]
This has been fixed in a rather unfortunate way

to fix it, make sure you and your dependencies don't use the `deser_borrows` feature, by disabling default features

```toml
twitch_api = { version = "0.7.0", default-features = false }
```

this will work for most requests, except those containing arrays
