### ISSUE TITLE
EventSub Over WebSocket

### ISSUE THREAD

**Issue by Nerixyz** [twitch-rs/twitch_api#290]
Twitch announced, that [EventSub over WebSockets is now in public beta](https://discuss.dev.twitch.tv/t/eventsub-websockets-are-now-available-in-open-beta/41639). This repo should implement the structures and requests to parse and manage the subscriptions and events.

Maybe there should be another project under the twitch-rs org that implements a client? Or more generally a project that has EventSub helpers for web-frameworks _and_ a WebSocket client?

**Comment by Emilgardis** [comment]
the websocket rust saga is horrible, tungstenite, seems to be the agreed upon base though.

How would a websocket client with `twitch_api` integration work?

for web-frameworks I can clearly see the benefits, as explained by you previously, but for websockets I'm unsure.


for pubsub currently, I do https://github.com/Emilgardis/twitch_discord_moderation/blob/main/src/subscriber.rs#L189

I'm not sure I see how to improve it with another tungstenite abstraction

**Comment by Emilgardis** [comment]
Reopening this as providing more functionality for clients remains open

**Comment by Emilgardis** [comment]
Should prioritize this as `.message` is probably around the corner now

**Comment by Emilgardis** [comment]
I think this has been sufficiently implemented now
