### ISSUE TITLE
Why can't I put multiple broadcaster_id in GetChannelInformationRequest?

### ISSUE THREAD

**Issue by B4TT3RY** [twitch-rs/twitch_api#294]
![image](https://user-images.githubusercontent.com/12368101/203216225-b1fe023e-adff-4947-a330-3e0d2d079d68.png)
Is it that I don't know how? Or is it not supported?

i used `twitch_api2 v0.6.1`

**Comment by Emilgardis** [comment]
good catch! This is indeed a fault in the library and should be supported.

in 2020 when this code was added this was not documented

https://web.archive.org/web/20201126161544/https://dev.twitch.tv/docs/api/reference

I'll make sure this gets added to 0.7.0

**Comment by Emilgardis** [comment]
To fix this https://github.com/twitch-rs/twitch_api/blob/2d4b88d8644af0c9e21826712778ed13622bf028/src/helix/endpoints/channels/get_channel_information.rs#L50 needs to be changed to

```rust
pub struct GetChannelInformationRequest<'a> {
    /// ID of the channel
    #[cfg_attr(not(feature = "deser_borrow"), serde(bound(deserialize = "'de: 'a")))]
    pub id: Cow<'a, [&'a types::UserIdRef]>,
}
```

and all other applicable places and documentation needs to be updated accordingly
