### ISSUE TITLE
another bug while decoding teaminfo

### ISSUE THREAD

**Issue by Glog78** [twitch-rs/twitch_api#325]
--- could not decode teaminfo error -> HelixRequestGetError(DeserializeError("{\"data\":null}", PathError { path: "data", error: Error("invalid type: null, expected a sequence"
, line: 1, column: 12) }, https://api.twitch.tv/helix/teams/channel?broadcaster_id=67130780, 200)) ---

i would like to use unwrap_or_default() << but the default trait  isn't implemented either. 

thanks again for your hard work.

**Comment by Emilgardis** [comment]
Interesting.

`{"data":null}` is not a valid response

https://dev.twitch.tv/docs/api/reference/#get-channel-teams says that 404 should be returned when "The broadcaster is not a member of a team."
<img width="769" alt="image" src="https://user-images.githubusercontent.com/1502855/216788871-d49faa03-224c-4bcd-bce4-6f838892fd0e.png">

**Comment by Emilgardis** [comment]
Aha, https://github.com/twitchdev/issues/issues/495

**Comment by Emilgardis** [comment]
fyi, instead of using `unwrap_or_default()` you could do

```
async fn get_teams() -> Result<BroadcasterTeam> {
    todo!()
}

let teams = get_teams().await.map(|d| d.data).unwrap_or_default();
```

The problem you experienced was that the `Response` struct doesn't have a default, but the actual response of `teams/channel` (`Vec<BroadcasterTeam>`) actually does.

**Comment by Glog78** [comment]
thank you for this little code , still learning :)
