### ISSUE TITLE
Clarify how or make it easier to pass in collections that are T: Iterator<Item=D> in builder functions for helix requests

### ISSUE THREAD

**Issue by Emilgardis** [twitch-rs/twitch_api#374]
This came up in discussion over at [Twitch API Discord](https://discord.com/channels/325552783787032576/1113231411483254814/1113240481648885812)

currently, it can be hard to reason how to deal with a method like

```rs
fn(Self, impl Into<Cow<'a, [&'a Borrowed]>>)
```

we have a bunch of these after #280 

One way to deal with this, given we have a `Vec<String>`, is

```rust
fn builder(s: impl Into<Cow<'a, [&'a Borrowed]>>) -> Foo {
    todo!()
}

fn bar(items: Vec<String>) {
    let items: Vec<&Borrowed> = items.iter().map(Into::into).collect();
    builder(items)
}
```

but coming up with this is not apparent.

This is related to https://github.com/twitch-rs/twitch_api/issues/114#issuecomment-1323517268 where we would make the allocation optional

**Comment by Emilgardis** [comment]
We could clarify in the documentation for the methods how to do this, or make new methods that take `impl Iterator<Item = impl Into<&'a Borrowed>>` which are then collected and put in a `Cow::Owned`.

I think I prefer the second alternative, since one would have to do an allocation either way if you have a `Vec<Owned>`.


@laundmo also mentions in the discord thread a solution that would involve a `CollectionRef` which abstracts over a collection, this would work for the `impl Iterator` route, and it would also work for a route where we make the stored collection in the `Request` generic over collection for those fields, albeit at a cost of more generics on that specific request.

**Comment by laundmo** [comment]
heres my CollectionRef idea:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=14019aa8f991b7ec5eef82f29879a459

a great advantage is that this works on many collections and individual items

**Comment by Emilgardis** [comment]
This could also be applied for the [client ext methods](https://github.com/twitch-rs/twitch_api/blob/main/src/helix/client/client_ext.rs) which currently takes `impl AsRef<[&'client types::CategoryIdRef]>`

**Comment by Emilgardis** [comment]
also experimented wuth 


```
fn into_slice_cow(self) -> std::borrow::Cow<'a, [R]>
    where
        Self: Sized,
        [R]: ToOwned,
        R: Sized + 'a, {
        match self {
            std::borrow::Cow::Borrowed(b) => {
                std::borrow::Cow::Borrowed(std::slice::from_ref(b.into()))
            }
            std::borrow::Cow::Owned(o) => {
                let a: std::borrow::Cow<'_, R> = std::borrow::Cow::Owned(o.into());

                let a = std::slice::from_ref(a.as_ref());

                std::borrow::Cow::Borrowed(a)
            }
        }
    }
```

**Comment by Emilgardis** [comment]
improved with #359
