### ISSUE TITLE
No login on validationg token

### ISSUE THREAD

**Issue by zxcqirara** [twitch-rs/twitch_api#430]
When I run `validate_token`, it returns `ValidatedToken` struct with `login: None`. Client's id and secret are correct, what can be wrong?

**Comment by Nerixyz** [comment]
Which type of token are you using? [App access tokens](https://dev.twitch.tv/docs/authentication/#app-access-tokens) don't have a user associated with them, thus `validate_token` won't return a populated `login`.

**Comment by zxcqirara** [comment]
Oh, really, I messed this moment

**Comment by zxcqirara** [comment]
(If somebody (or me if I'll forget) will also be curious about it, these is an example of using user token: https://github.com/twitch-rs/twitch_oauth2/blob/main/examples/auth_flow.rs)
