### ISSUE TITLE
Multiple missing eventsub messages (not beta)

### ISSUE THREAD

**Issue by EthanZeigler** [twitch-rs/twitch_api#467]
**Description**

Several message types are missing from eventsub. These were all added in the past few months.
- https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchannel_points_automatic_reward_redemptionadd
- https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelmoderate-v2
- https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelunban_requestcreate
- https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelunban_requestresolve
- https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelsuspicious_usermessage
- https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelsuspicious_userupdate
- https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelvipadd
- https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelvipremove
- https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelwarningacknowledge
- https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelwarningsend
- https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#conduitsharddisabled
- https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#userwhispermessage

**Comment by EthanZeigler** [comment]
this is non exhaustive. I may have missed some

**Comment by Emilgardis** [comment]
Most of these are adressed with #457, also we have a [handy tracker](https://twitch-rs.github.io/twitch_api/twitch_api/eventsub/index.html#implemented-subscriptions) in the documentation showing what's missing ;)
`Conduit Shard Disabled` [is implemented](https://twitch-rs.github.io/twitch_api/twitch_api/eventsub/conduit/shard/disabled/index.html)

Going to close this issue as it's not very interesting to keep open. But thank you for the effort! Feel free to make a pr to implement https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#userwhispermessage as that's the only one on your list that's missing and is useful
