### ISSUE TITLE
Figure out a good way to do releases.

### ISSUE THREAD

**Issue by Emilgardis** [twitch-rs/twitch_api#9]
Implement a better way to do releases.

I think I'd want a script that does the following

1. run the script with arguments `$bump crates_to_update <release|major|minor|patch>` 
2. script changes all references of version number where needed and Cargo.toml of the bumped crates (but only the bumped crate if bump is minor and it's a library we're bumping). 
3. script or user updates changelog if needed.
4. script creates a commit with the necessary changes, one for each crate.
5. pr is made, and is then merged. CI on push to master, will for each new commit with commit message with a known structure, ci kicks in and publishes the crate bumped in commit to crates and makes a tag (and a release with changelog , entry, and binary if applicable)
6. ???
7. profit!!!

To test this I think it's safest to work in another repo and setup a local crates registry. If [act](https://github.com/nektos/act) worked on wsl with actions-rs it would be really easy to test, but currently there's an error with cargo action not finding binaries.

I'll chime in here if I make any progress on this.

**Comment by Emilgardis** [comment]
I think this suggests I do need to split this repo into two, I could do that quite easily but maintenance would be really annoying.

**Comment by Emilgardis** [comment]
I've split off the oauth2 crate into https://github.com/Emilgardis/twitch_oauth2 . Still some work left to sperate it from this crate but don't have the time yet

**Comment by simonsan** [comment]
You could try [cargo release](https://github.com/sunng87/cargo-release) with a [`release.toml`](https://github.com/sunng87/cargo-release/blob/master/release.toml) in `$crate-root`.

**Comment by Emilgardis** [comment]
@simonsan thanks for the suggestion, but I already use cargo-release ;). think I could add it to a CI workflow that triggers on something. For me the problem is what should trigger that workflow.

I definitely need to start using keep-a-changelog also to profit more from 

Are there any examples of using cargo-release in CI available?

**Comment by Emilgardis** [comment]
github actions has a [`release`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onevent_nametypes) event I could use I think, sounds promising

**Comment by simonsan** [comment]
> 
> 
> github actions has a [`release`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onevent_nametypes) event I could use I think, sounds promising

https://github.com/simonsan/openage-win-dependencies/blob/master/.github/workflows/build-win-deps.yml

It's a tiny bit outdated, but like this you can use Github actions to release something. but here for example is the corresponding action:
https://github.com/marketplace/actions/upload-files-to-a-github-release

As a trigger you can use a branch called releases where the commits get pushed to:
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

Or you can read this one about triggering workflows:
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows

**Comment by simonsan** [comment]
I found also a nice CLI tool written in rust to make the changelog situation a bit easier:
https://github.com/saschagrunert/git-journal

**Comment by Emilgardis** [comment]
I think this can be considered solved with the current setup, releases are as simple as

1. `cargo release ...`
2. make a pr
3. merge
4. ci publishes

an improvement that could be made is to only have to do a version bump and let ci do `cargo release <version> --execute` but I think this is good enough
